# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    -   id: ruff
        args: ["--fix"]
    -   id: ruff-format
-   repo: https://github.com/python-poetry/poetry
    rev: 8136c5fe8e54d57e6a646b3309b805e2c5fc084d
    hooks:
    -   id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
       - id: mypy
         language: system
         pass_filenames: false
         args: ['.']
ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
