[tool.poetry]
name = "datascience-project"
version = "0.1.0"
description = ""
authors = ["SergRusetskiy1974 <sergrus1974@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
fastapi = "^0.112.0"
uvicorn = {extras = ["standard"], version = "^0.30.6"}
sqlalchemy = "^2.0.32"
psycopg2 = "^2.9.9"
alembic = "^1.13.2"
tensorflow-io-gcs-filesystem = "0.29.0"
tensorflow = "^2.17.0"
opencv-python = "^4.10.0.84"
scikit-learn = "^1.5.1"
matplotlib = "3.7.0"
kiwisolver = "1.4.5"

[tool.mypy]
ignore_missing_imports = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.0"
pre-commit = "^3.8.0"
mypy = "^1.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
