"""ref parkings2

Revision ID: 8e81192d197f
Revises: fb6de44f1b1c
Create Date: 2024-08-26 11:20:42.435103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e81192d197f'
down_revision: Union[str, None] = 'fb6de44f1b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(), nullable=False))
    op.add_column('payments', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'description')
    op.drop_column('payments', 'payment_date')
    # ### end Alembic commands ###
