"""ref parkings

Revision ID: fb6de44f1b1c
Revises: be9f4a30585b
Create Date: 2024-08-26 10:54:27.657428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6de44f1b1c'
down_revision: Union[str, None] = 'be9f4a30585b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parkings', 'duration')
    op.drop_column('parkings', 'cost')
    op.drop_column('payments', 'paid_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('paid_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('parkings', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parkings', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
