"""ref rate_cars

Revision ID: be9f4a30585b
Revises: 603f573514e2
Create Date: 2024-08-26 10:11:04.855899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9f4a30585b'
down_revision: Union[str, None] = '603f573514e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('rate_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cars', 'rates', ['rate_id'], ['id'])
    op.drop_constraint('parkings_rate_id_fkey', 'parkings', type_='foreignkey')
    op.drop_column('parkings', 'rate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkings', sa.Column('rate_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('parkings_rate_id_fkey', 'parkings', 'rates', ['rate_id'], ['id'])
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'rate_id')
    # ### end Alembic commands ###
