"""add parking is_active

Revision ID: d98e5af6fee9
Revises: f31d68fd695d
Create Date: 2024-08-26 08:46:06.545584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98e5af6fee9'
down_revision: Union[str, None] = 'f31d68fd695d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkings', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parkings', 'is_active')
    # ### end Alembic commands ###
